"""First Danish draft for MageQuit (status "machine": every line still needs a human review).

Usage: python draft_da.py <strings.json>

- Fills empty Danish texts from TEXT below (never touches entries edited by a person).
- Adds REGEX entries for text the game builds at runtime ("Round 3 of 5", "X has left the battle!").
- Removes DROP entries: debug output, internal names and string fragments that never appear on
  screen on their own (the regexes cover the assembled sentences instead).
"""
import json
import sys

TEXT = {
    # --- General UI ---
    "* Daily Win Bonus *": "* Daglig sejrsbonus *",
    "+          TO JOIN": "+          FOR AT DELTAGE",
    "--- or ---": "--- eller ---",
    "(Highly recommended)": "(Stærkt anbefalet)",
    "(or c-stick up)": "(eller C-stick op)",
    "1v1": "1v1",
    "3v3": "3v3",
    "2nd Place": "2. plads",
    "1st Place": "1. plads",
    "3rd Place": "3. plads",
    "A member of your party has left.": "Et medlem af din gruppe er gået.",
    "ADD         PLAYER": "TILFØJ         SPILLER",
    "Aim": "Sigt",
    "All wireless controllers (not including Joy-Cons) will be treated as USB GameCube controllers. Use this setting if your wireless controllers have both ZL and ZR buttons.":
        "Alle trådløse controllere (undtagen Joy-Cons) behandles som USB GameCube-controllere. Brug denne indstilling, hvis dine trådløse controllere har både ZL- og ZR-knapper.",
    "ANNOUNCEMENTS": "MEDDELELSER",
    "Archmage": "Ærkemagiker",
    "Auto": "Auto",
    "Back": "Tilbage",
    "Beautiful": "Smuk",
    "Blue Team": "Blåt hold",
    "Red Team": "Rødt hold",
    "Yellow Team": "Gult hold",
    "No Team": "Intet hold",
    "Bot Difficulty": "Bot-sværhedsgrad",
    "Bottomless Pit": "Bundløst hul",
    "CANCEL": "ANNULLÉR",
    "CAPE": "KAPPE",
    "change mapping": "skift tildeling",
    "Chaos\n": "Kaos\n",
    "CHECK THE SCORES": "SE RESULTATERNE",
    "CHOOSE A SIDE FOR TEAMS OR STAY IN CENTER FOR FFA": "VÆLG EN SIDE FOR HOLD, ELLER BLIV I MIDTEN FOR ALLE MOD ALLE",
    "CHOOSE YOUR        SPELL": "VÆLG DIN        BESVÆRGELSE",
    "Choose Your Set": "Vælg dit sæt",
    "Classic Draft": "Klassisk udvælgelse",
    "Classic GameCube": "Klassisk GameCube",
    "Click to Melee": "Klik for nærkamp",
    "Close": "Luk",
    "Cloth": "Stof",
    "Code copied!": "Kode kopieret!",
    "COMING SOON": "KOMMER SNART",
    "Coming Soon?": "Kommer snart?",
    "Compete for game keys, gems, and XP in official monthly MageQuit tournaments.":
        "Kæmp om spilnøgler, ædelsten og XP i officielle månedlige MageQuit-turneringer.",
    "Compete in community organized events.\nMore info at magequit.com/league":
        "Deltag i events arrangeret af fællesskabet.\nMere info på magequit.com/league",
    "Competitive": "Konkurrence",
    "Connecting...": "Forbinder...",
    "Controllers": "Controllere",
    "Couch": "Sofa",
    "CURVE": "KURVE",
    "Curve Left": "Kurve til venstre",
    "Curve Right": "Kurve til højre",
    "Custom": "Tilpasset",
    "Customize": "Tilpas",
    "Daily Win Bonus": "Daglig sejrsbonus",
    "Daily Win Bonus Available": "Daglig sejrsbonus klar",
    "Damage:": "Skade:",
    "DANGER": "FARE",
    "Deaths:": "Dødsfald:",
    "Kills:": "Drab:",
    "Healing:": "Heling:",
    "Default": "Standard",
    "Defensive": "Defensiv",
    "Deflect": "Afbøj",
    "DETERMINING PINGS": "MÅLER PING",
    "Difficulty": "Sværhedsgrad",
    "Do Tutorial First": "Tag øvelsen først",
    "Early Access v1.5": "Early Access v1.5",
    "Elements": "Elementer",
    "Enabled": "Slået til",
    "Enter code...": "Indtast kode...",
    "EQUIP": "TAG PÅ",
    "EQUIPPED": "PÅTAGET",
    "Equipped": "Påtaget",
    "Fantastic": "Fantastisk",
    "Fast": "Hurtig",
    "Fastest": "Hurtigst",
    "FEET": "FØDDER",
    "FFA": "AMA",
    "First Full Game of the Day": "Dagens første hele spil",
    "FOR MAGEQUIT": "TIL MAGEQUIT",
    "For the epileptic.": "For epileptikere.",
    "Forfeit": "Giv op",
    "Free For All": "Alle mod alle",
    "Friend #1": "Ven #1",
    "FRIENDS LIST": "VENNELISTE",
    "Full Screen": "Fuld skærm",
    "Game Mode": "Spiltilstand",
    "GAME PAUSED": "SPILLET ER PAUSET",
    "Game Started": "Spillet er startet",
    "Game Quit": "Spillet er afsluttet",
    "GEMS": "ÆDELSTEN",
    "Gems": "Ædelsten",
    "Go head to head, starting with all 7 spells.": "Mand mod mand, med alle 7 besværgelser fra start.",
    "Go head to head, starting with all 7 spells.\nThis queue opens at 9pm EST each night.":
        "Mand mod mand, med alle 7 besværgelser fra start.\nKøen åbner kl. 3 dansk tid hver nat.",
    "Good": "God",
    "Graphics": "Grafik",
    "HANDS": "HÆNDER",
    "HAT": "HAT",
    "Health": "Liv",
    "HOLD POSITION": "HOLD POSITIONEN",
    "Hold Position": "Hold positionen",
    "In Air": "I luften",
    "Invite": "Invitér",
    "IQ": "IQ",
    "ITEM": "GENSTAND",
    "Join": "Deltag",
    "Join / Ready": "Deltag / Klar",
    "Join our community!": "Bliv en del af fællesskabet!",
    "Join our Community!": "Bliv en del af fællesskabet!",
    "Join our Monthly Tournament!": "Deltag i vores månedlige turnering!",
    "JOIN QUEUE": "STIL DIG I KØ",
    "Join successful!": "Du er med!",
    "Keyboard": "Tastatur",
    "Keyboard Controls": "Tastaturstyring",
    "Keyboard Mappings": "Tastaturtildelinger",
    "LATE\nJOIN\nBONUS": "SEN\nSTART\nBONUS",
    "Learn the basics of movement, spell casting, spell curving, and drafting.":
        "Lær det grundlæggende: bevægelse, at kaste og kurve besværgelser, og udvælgelse.",
    "Learn to Play!": "Lær at spille!",
    "Left": "Venstre",
    "Right": "Højre",
    "Up": "Op",
    "Left Click": "Venstreklik",
    "Right Click": "Højreklik",
    "Less chance. More sweat. Ideal for tournaments and ranked play.":
        "Mindre held. Mere sved. Ideel til turneringer og rangerede kampe.",
    "LEVEL": "NIVEAU",
    "LEVEL 15 REQUIRED": "KRÆVER NIVEAU 15",
    "Level 15 Required": "Kræver niveau 15",
    "Level 5 Required": "Kræver niveau 5",
    "Level Up": "Niveau op",
    "Load\nState": "Indlæs\ntilstand",
    "Load State": "Indlæs tilstand",
    "Save\nState": "Gem\ntilstand",
    "Save State": "Gem tilstand",
    "Logging": "Logning",
    "LOOKING FOR A MATCH": "LEDER EFTER EN KAMP",
    "Match Complete": "Kampen er slut",
    "MATCH WILL BEGIN SHORTLY": "KAMPEN BEGYNDER OM LIDT",
    "MATCHMAKER RESTARTING...": "MATCHMAKER GENSTARTER...",
    "MAX": "MAKS",
    "Medium": "Mellem",
    "Melee": "Nærkamp",
    "Mercy Rule": "Nåderegel",
    "Mirror": "Spejl",
    "Mirror Needs Even Teams": "Spejl kræver lige store hold",
    "Modern GameCube": "Moderne GameCube",
    "More Info": "Mere info",
    "Mouse": "Mus",
    "Mouse 0": "Mus 0",
    "Mouse 1": "Mus 1",
    "Move": "Bevæg",
    "Movement": "Bevægelse",
    "Music": "Musik",
    "Music volume level.": "Musikkens lydstyrke.",
    "Sound": "Lyd",
    "N/A": "–",
    "Nature": "Natur",
    "NEW ELEMENT UNLOCKED": "NYT ELEMENT LÅST OP",
    "NEW Keyboard Mapper!": "NY tastaturopsætning!",
    "New Unlockable Skins!": "Nye skins at låse op!",
    "New!": "Ny!",
    "NEW!": "NY!",
    "Next Tip": "Næste tip",
    "NEXT TOURNAMENT": "NÆSTE TURNERING",
    "NO": "NEJ",
    "YES": "JA",
    "Yes": "Ja",
    "None": "Ingen",
    "None Scheduled": "Ingen planlagt",
    "Not Connected": "Ikke forbundet",
    "Not Party Host": "Ikke gruppens vært",
    "Now": "Nu",
    "Number of Bots": "Antal botter",
    "Off": "Fra",
    "On": "Til",
    "On\n": "Til\n",
    "OKAY": "OK",
    "Online": "Online",
    "ONLINE 3v3 TOURNAMENT": "ONLINE 3v3-TURNERING",
    "OPPONENT": "MODSTANDER",
    "Options": "Valgmuligheder",
    "Party": "Gruppe",
    "PARTY": "GRUPPE",
    "Party Bonus": "Gruppebonus",
    "PARTY ONLY": "KUN GRUPPE",
    "Party Too Large": "Gruppen er for stor",
    "Party Too Small": "Gruppen er for lille",
    "Party of 2 (+10%)": "Gruppe på 2 (+10%)",
    "Party of 3 (+15%)": "Gruppe på 3 (+15%)",
    "Party of 4 (+18%)": "Gruppe på 4 (+18%)",
    "PINGS": "PING",
    "PINGS FAILED": "PING MISLYKKEDES",
    "PING FAILED": "PING MISLYKKEDES",
    "Play": "Spil",
    "PLAY": "SPIL",
    "Play a 3v3 team game with some extra objectives.": "Spil 3v3 på hold med ekstra mål.",
    "Play a 3v3 team game with some extra objectives.\nThis queue is still under development.":
        "Spil 3v3 på hold med ekstra mål.\nDenne kø er stadig under udvikling.",
    "Play a 4v4 or 5v5 team game with extra objectives.": "Spil 4v4 eller 5v5 på hold med ekstra mål.",
    "Play with 5 other wizards in a free for all battle.": "Kæmp mod 5 andre troldmænd, alle mod alle.",
    "Play with friends for extra XP": "Spil med venner for ekstra XP",
    "Please update MageQuit to play online.": "Opdatér MageQuit for at spille online.",
    "Plug in a controller": "Tilslut en controller",
    "Practice Range": "Øvebane",
    "PRACTICE RANGE UNLOCKED": "ØVEBANE LÅST OP",
    "Presets": "Forudindstillinger",
    "PRESS": "TRYK",
    "PRESS           TO JOIN": "TRYK           FOR AT DELTAGE",
    "PRESS ANY BUTTON": "TRYK PÅ EN KNAP",
    "Press Any Button To Play": "Tryk på en knap for at spille",
    "PRESS ANY KEY": "TRYK PÅ EN TAST",
    "Primary": "Primær",
    "Primary Spell": "Primær besværgelse",
    "Secondary": "Sekundær",
    "Ultimate": "Ultimativ",
    "Utility": "Hjælpemiddel",
    "Pro Controller": "Pro Controller",
    "QUICK PLAY\nTEAMS": "HURTIG KAMP\nHOLD",
    "QUICKPLAY": "HURTIG KAMP",
    "Quit": "Afslut",
    "Random": "Tilfældig",
    "RANKED": "RANGERET",
    "RANKED 1v1": "RANGERET 1v1",
    "Ranked": "Rangeret",
    "Unranked": "Urangeret",
    "Ready": "Klar",
    "Redeem": "Indløs",
    "Redeem Code": "Indløs kode",
    "Refresh Rate": "Opdateringshastighed",
    "Registration Closed": "Tilmeldingen er lukket",
    "Registration Open": "Tilmeldingen er åben",
    "Registration Open!": "Tilmeldingen er åben!",
    "Report Bug": "Rapportér fejl",
    "RESET": "NULSTIL",
    "Reset\nAll": "Nulstil\nalt",
    "Reset\nCDs": "Nulstil\nCD'er",
    "Reset All": "Nulstil alt",
    "Reset Cooldowns": "Nulstil nedkøling",
    "Resolution": "Opløsning",
    "Resume": "Fortsæt",
    "room code:": "rumkode:",
    "Rounds": "Runder",
    "SAVE": "GEM",
    "Scan with phone camera": "Scan med telefonens kamera",
    "Screen Shake": "Skærmrystelser",
    "seconds\nelapsed": "sekunder\ngået",
    "seconds\nexpected": "sekunder\nforventet",
    "See Error": "Se fejl",
    "SELECT MORE MODES FOR SHORTER QUEUE TIMES": "VÆLG FLERE TILSTANDE FOR KORTERE VENTETID",
    "Server Maintenance in": "Servervedligeholdelse om",
    "SERVER MAINTENANCE COMPLETE!": "SERVERVEDLIGEHOLDELSE FÆRDIG!",
    "SET": "SÆT",
    "Set Name": "Sættets navn",
    "Settings": "Indstillinger",
    "SHIRT": "TRØJE",
    "SHOWDOWN": "OPGØR",
    "Shown In Game": "Vises i spillet",
    "Hidden In Game": "Skjult i spillet",
    "Sign Up": "Tilmeld",
    "SIGN UP NOW": "TILMELD DIG NU",
    "Simple": "Simpel",
    "Space Bar": "Mellemrum",
    "Spell Combos": "Kombinationer",
    "Spell Name": "Besværgelsens navn",
    "Spell Selection": "Valg af besværgelser",
    "SPELLS": "BESVÆRGELSER",
    "Spells are drafted one at a time after each round, starting with the wizard with the shortest beard.":
        "Besværgelserne vælges én ad gangen efter hver runde, begyndende med troldmanden med det korteste skæg.",
    "Spells are drafted one at a time after each round, starting with the wizard with the shortest beard. Not ideal for 7+ players.":
        "Besværgelserne vælges én ad gangen efter hver runde, begyndende med troldmanden med det korteste skæg. Ikke ideelt til 7+ spillere.",
    "SPOILS": "BYTTE",
    "STAFF": "STAV",
    "Stage": "Bane",
    "Start": "Start",
    "Start Free For All": "Start alle mod alle",
    "Start Teams": "Start hold",
    "SUDDEN DEATH": "SUDDEN DEATH",
    "Switch to Mouse": "Skift til mus",
    "Switch to WASD": "Skift til WASD",
    "System Information": "Systeminformation",
    "Teams": "Hold",
    "Thank you for reviewing MageQuit!": "Tak, fordi du anmelder MageQuit!",
    "That party is already full!": "Den gruppe er allerede fuld!",
    "THE VOLCANO": "VULKANEN",
    "THIS DIAGRAM IS NOT ACCURATE AS\nCONTROLS HAVE BEEN CUSTOMIZED": "DIAGRAMMET ER IKKE KORREKT,\nDA STYRINGEN ER TILPASSET",
    "TIP:  Ice Crystals expire if you don't create a new one within 5 seconds.":
        "TIP:  Iskrystaller forsvinder, hvis du ikke laver en ny inden for 5 sekunder.",
    "TIP:  Non Joy-Con controllers can be mapped as GameCube or Pro Controllers in Settings.":
        "TIP:  Andre controllere end Joy-Cons kan sættes op som GameCube- eller Pro Controllere under Indstillinger.",
    "TIP:  You can curve your spells with the triggers.": "TIP:  Du kan kurve dine besværgelser med aftrækkerne.",
    "TO UNLOCK": "FOR AT LÅSE OP",
    "Total": "I alt",
    "TOURNAMENT": "TURNERING",
    "Try disabling XInput under Settings if you can't connect more controllers.":
        "Prøv at slå XInput fra under Indstillinger, hvis du ikke kan tilslutte flere controllere.",
    "Tutorial": "Øvelse",
    "Tutorial Complete!": "Øvelsen er gennemført!",
    "UNLOCK": "LÅS OP",
    "Waiting for input": "Venter på input",
    "Wardrobe": "Garderobe",
    "Warning:  Leaving a ranked game counts as a 0-3 loss.": "Advarsel:  Forlader du en rangeret kamp, tæller det som et 0-3-nederlag.",
    "WATCH THE STREAM": "SE STREAMEN",
    "Win a match daily for extra XP & gems": "Vind en kamp hver dag for ekstra XP og ædelsten",
    "WINNER BY FORFEIT": "VINDER, DA MODSTANDEREN GAV OP",
    "Wired Controller Map": "Kablet controller-opsætning",
    "Wireless Controller Map": "Trådløs controller-opsætning",
    "Worst graphics. Best framerate.": "Dårligste grafik. Bedste billedhastighed.",
    "Best graphics. Lowest framerate. If your computer is awesome, your framerate will be fine here too.":
        "Bedste grafik. Laveste billedhastighed. Har du en vild computer, kører det også fint her.",
    "Would you like to try": "Vil du prøve",
    "XInput On": "XInput til",
    "XInput Off": "XInput fra",
    "VSync On": "VSync til",
    "Windowed": "Vindue",
    "← Triple-click to report bug": "← Tredobbeltklik for at rapportere en fejl",
    "Accepted": "Accepteret",
    "Attack": "Angrib",
    "Battle": "Kamp",
    "Chat": "Chat",
    "Colors": "Farver",
    "First Spell Draft": "Første besværgelsesudvælgelse",
    "2-Spell Draft": "Udvælgelse af 2 besværgelser",
    "Name": "Navn",
    "No Modes Selected": "Ingen tilstande valgt",
    "No Valid Modes": "Ingen gyldige tilstande",
    "Not Allowed": "Ikke tilladt",
    "Price": "Pris",
    "RESCAN": "SØG IGEN",
    "Walk": "Gå",
    "Lava": "Lava",
    "Listening...": "Lytter...",
    "Too many wizards on one team.": "For mange troldmænd på ét hold.",
    "Too many elements banned for that spell selection mode.": "For mange elementer er udelukket for den måde at vælge besværgelser på.",
    "You make your own rules. But if you want suggestions, you will find them here.": "Du laver selv reglerne. Men vil du have forslag, finder du dem her.",
    "Wizards have medium health for a standard-speed game.": "Troldmændene har middel liv for et spil i normalt tempo.",
    "Wizards have low health for faster rounds.": "Troldmændene har lavt liv for hurtigere runder.",
    "Wizards have high health for longer rounds. Good for the sports stage if you want the puck to be more effective.":
        "Troldmændene har højt liv for længere runder. Godt til sportsbanen, hvis pucken skal gøre mere skade.",
    "Who doesn't like sports?": "Hvem kan ikke lide sport?",
    "Two halves of an island connected by 2 bridges.": "To halvdele af en ø forbundet af 2 broer.",
    "The ideal mode for 1v1. Same as Mirror, except players are given 3 sets of random spells to choose from.":
        "Den ideelle tilstand til 1v1. Som Spejl, men spillerne får 3 sæt tilfældige besværgelser at vælge imellem.",
    "The game will run at your monitor's refresh rate.": "Spillet kører med din skærms opdateringshastighed.",
    "The game will run at the maximum framerate your computer can handle.": "Spillet kører med den højeste billedhastighed, din computer kan klare.",
    "Too Many Mages On Ice": "For mange magikere på isen",
    "YOU SURE?": "ER DU SIKKER?",
    "Cancel": "Annullér",
    "Unlimited": "Ubegrænset",
    "Fire": "Ild",
    "Ready Up": "Gør klar",

    # --- Tutorial hints (shown next to spells) ---
    "(away from target but stay\n  near them)": "(væk fra målet, men bliv\n  tæt på)",
    "(away from target but stay near the ball)": "(væk fra målet, men bliv tæt på bolden)",
    "(away from target but stay near them)": "(væk fra målet, men bliv tæt på)",
    "(before casting)": "(før kastet)",
    "(throw worm out into lava, then go back\nthrough and close it after enemy is pulled in)":
        "(kast ormen ud i lavaen, gå tilbage\ngennem den, og luk den, når fjenden er trukket ind)",
    "(tip before casting)": "(tip før kastet)",
    "(while casting)": "(mens du kaster)",
    "aim into lava": "sigt ud i lavaen",
    "attach to shield": "fastgør til skjold",
    "away from target": "væk fra målet",
    "hit ball": "ram bolden",
    "hit enemy": "ram fjenden",
    "snag enemy wizard": "fang den fjendtlige troldmand",
    "throw away from enemy": "kast væk fra fjenden",
    "must not be swept": "må ikke blive fejet væk",
    "time with urchain collision": "time det med søpindsvinets sammenstød",
    "Somer Assault can be casted twice to jump.": "Saltoangreb kan kastes to gange for at hoppe.",

    # --- Combo names (spell combos list; puns kept loose) ---
    "5 Essential Minerals:": "5 essentielle mineraler:",
    "Blast Fishing:": "Bombefiskeri:",
    "Brittle End:": "Skrøbelig slutning:",
    "Cold Front:": "Koldfront:",
    "Crowded Sauna:": "Overfyldt sauna:",
    "Death Box:": "Dødsboks:",
    "Death Charge:": "Dødsstorm:",
    "Death Taxi:": "Dødstaxa:",
    "Doing Time:": "Afsoner:",
    "Doom Loop:": "Undergangsløkke:",
    "Doomerang:": "Dommerang:",
    "EmJov 3-Piece:": "EmJov 3-styk:",
    "EmJov Special:": "EmJov special:",
    "Grave Robber:": "Gravrøver:",
    "Hammer Time:": "Hammertid:",
    "Hang Ten:": "Hang Ten:",
    "Hold my Stones:": "Hold mine sten:",
    "Hooke, Line, and Sinker:": "Krog, line og synk:",
    "Hop on Pop:": "Hop på far:",
    "Houston Liftoff:": "Houston, letter:",
    "How Did I Die:": "Hvordan døde jeg:",
    "Live Bait:": "Levende madding:",
    "Marty Party:": "Marty-fest:",
    "Paddle Ball:": "Paddleball:",
    "Rock Box:": "Stenboks:",
    "Rush Hour:": "Myldretid:",
    "Sea Friends:": "Havvenner:",
    "Shock Collar:": "Stødhalsbånd:",
    "Spartan Toss:": "Spartansk kast:",
    "Spartan Trebuchet:": "Spartansk blide:",
    "Spiked Collar:": "Pigget halsbånd:",
    "String Cheese:": "Ostestrenge:",
    "Supercharge+:": "Superladning+:",
    "Supercharge:": "Superladning:",
    "Tear Jerker:": "Tåreperser:",
    "The Long Con:": "Det lange fupnummer:",
    "Vab Worm:": "Vab-orm:",
    "Vine Bomb:": "Rankebombe:",
    "Voltage Spike:": "Spændingsspids:",
    "Whiplash:": "Piskesmæld:",
    "You Were The Chosen One:": "Du var den udvalgte:",

    # --- Spell descriptions ---
    "Accelerating charge with high knockback and damage.": "Accelererende stormløb med høj tilbageslag og skade.",
    "Ball of fire that deals moderate damage and knockback.": "Ildkugle med moderat skade og tilbageslag.",
    "Boomerang that tries to return to the caster. Collisions with other units cause the boomerang to grow in size.":
        "Boomerang, der prøver at vende tilbage til kasteren. Sammenstød med andre enheder får den til at vokse.",
    "Caster leaps high into the air and detonates your Crystals upon landing, dealing heavy damage, creating platforms, and immobilizing units within range.":
        "Kasteren springer højt op i luften og sprænger dine krystaller ved landing. Det giver stor skade, laver platforme og lammer enheder inden for rækkevidde.",
    "Casts a Crystal into the air that deals damage upon landing. Cast distance is determined by spell curve. Upon reactivation, the Crystal is reeled in. On cast, your Crystals become Hooked, attaching themselves on contact.":
        "Kaster en krystal op i luften, der giver skade, når den lander. Afstanden bestemmes af kurven. Ved genaktivering hales krystallen ind. Ved kast bliver dine krystaller krogede og hægter sig fast ved kontakt.",
    "Casts your previous spell again.": "Kaster din forrige besværgelse igen.",
    "Conjures a jet of water that pushes the caster backward and enemies away.": "Fremmaner en vandstråle, der skubber kasteren bagud og fjenderne væk.",
    "Conjures a pyre that damages wizards and grows as it incinerates other spells.": "Fremmaner et bål, der skader troldmænd og vokser, når det brænder andre besværgelser op.",
    "Creates a bubble around the caster that prevents one instance of damage and heals for that amount instead.":
        "Laver en boble om kasteren, der blokerer én skade og i stedet heler lige så meget.",
    "Creates a growing wave that slows and carries your enemies away.": "Laver en voksende bølge, der bremser dine fjender og skyller dem væk.",
    "Creates a protective gale around the caster that redirects spells forward.": "Laver en beskyttende storm om kasteren, der sender besværgelser fremad igen.",
    "Creates a rock wall in front of the caster to block wizards and spells.": "Laver en stenmur foran kasteren, der blokerer troldmænd og besværgelser.",
    "Creates a static field that prevents half of the damage taken. After 4 seconds, the field discharges, dealing full damage back to each source.":
        "Laver et statisk felt, der halverer skaden, du tager. Efter 4 sekunder aflades feltet og giver fuld skade tilbage til hver kilde.",
    "Creates a vacuum around a target, pulling in wizards and spells.": "Laver et vakuum om et mål, der suger troldmænd og besværgelser ind.",
    "Disk that, on contact, summons a clone that mimics your movement and explodes if killed. Can be reactivated to swap positions with clone.":
        "Skive, der ved kontakt fremkalder en klon, som efterligner dine bevægelser og eksploderer, hvis den dræbes. Genaktivér for at bytte plads med klonen.",
    "Encases a target in 3 stone walls that accelerate toward the caster.": "Indkapsler et mål i 3 stenmure, der accelererer mod kasteren.",
    "Extra-long dash that chains up to 7 nearby units when successfully hit, pulling all affected units to starting point of dash.":
        "Ekstra langt spurt, der ved træf lænker op til 7 nærliggende enheder og trækker dem alle til spurtens startpunkt.",
    "Fast melee attack with high knockback. If missed, the caster falls over.": "Hurtigt nærkampsangreb med højt tilbageslag. Ved bom falder kasteren omkuld.",
    "Fires a barrage of 5 icicles in the cast direction, dealing damage and creating new Crystals after a delay. On cast, your Crystals become Inert, just sitting there.":
        "Affyrer en byge af 5 istapper i kasteretningen, der giver skade og laver nye krystaller efter et øjeblik. Ved kast bliver dine krystaller inaktive og ligger bare der.",
    "Flask that explodes on contact, creating a cloud that hurts enemies and heals allies over time.":
        "Flaske, der eksploderer ved kontakt og laver en sky, som skader fjender og heler allierede over tid.",
    "Frog that jumps 3 times, healing and bouncing all nearby wizards. Enemies only receive half healing.":
        "Frø, der hopper 3 gange og heler og kaster alle nærliggende troldmænd rundt. Fjender får kun halv heling.",
    "Glass shard with a high cooldown that refreshes if a unit is hit.": "Glasskår med lang nedkøling, der nulstilles, hvis en enhed rammes.",
    "Gust of wind that deals minor damage and knockback. Lowest cast time and longest range.":
        "Vindstød med lille skade og tilbageslag. Korteste kastetid og længste rækkevidde.",
    "Hammer that forces target wizard to cast the same spell type (e.g. melee, secondary) that the caster used previously, regardless of cooldown.":
        "Hammer, der tvinger mål-troldmanden til at kaste samme type besværgelse (f.eks. nærkamp, sekundær), som kasteren brugte sidst, uanset nedkøling.",
    "Heavy rock that deals moderate damage and high knockback. Highest cast time.": "Tung sten med moderat skade og højt tilbageslag. Længste kastetid.",
    "Hose that attaches on impact. Can be reactivated to swap positions with attached unit. Curving the reactivation will apply force.":
        "Slange, der hænger fast ved træf. Genaktivér for at bytte plads med enheden. Kurver du genaktiveringen, giver det et skub.",
    "Hourglass that attaches to a unit and detonates with upward force after 3 seconds.": "Timeglas, der hænger fast på en enhed og sprænger den opad efter 3 sekunder.",
    "Hurls a capacitor that attaches itself to a unit and explodes when it comes into contact with another unit.":
        "Kaster en kondensator, der hænger fast på en enhed og eksploderer, når den rører en anden enhed.",
    "Hurls a device that teleports you and creates 2 clones to surround your enemy. Clones mimic your spell casts and movement and explode if killed.":
        "Kaster en anordning, der teleporterer dig og laver 2 kloner, som omringer din fjende. Klonerne efterligner dine kast og bevægelser og eksploderer, hvis de dræbes.",
    "Hurls a snowball that becomes more deadly the further it travels and forms a Crystal on impact. On cast, your Crystals become Brittle, exploding on enemy contact.":
        "Kaster en snebold, der bliver farligere, jo længere den flyver, og danner en krystal ved træf. Ved kast bliver dine krystaller skrøbelige og eksploderer ved kontakt med fjender.",
    "Invokes a large boulder that petrifies units and creates walls in its wake.": "Påkalder en stor kampesten, der forstener enheder og efterlader mure i sit spor.",
    "Leech that attaches itself to an enemy, dealing damage over time. If collected, it heals based on the damage done.":
        "Igle, der suger sig fast på en fjende og giver skade over tid. Samler du den op, heler den efter den skade, den har gjort.",
    "Life preserver that absorbs one hit and creates a clone in your place, teleporting you behind the damaging wizard. Clones mimic your movement and explode if killed. Reactivate to swap with clone.":
        "Redningskrans, der tager ét træf og laver en klon i dit sted, mens du teleporteres om bag den troldmand, der ramte dig. Kloner efterligner dine bevægelser og eksploderer, hvis de dræbes. Genaktivér for at bytte med klonen.",
    "Lightning bolt that deals high damage and very high knockback. High cast time.": "Lynnedslag med høj skade og meget højt tilbageslag. Lang kastetid.",
    "Lightning bug that pulls in the nearest unit within its range. After 2 pulls, the bug explodes, launching nearby units upward.":
        "Ildflue, der trækker den nærmeste enhed inden for rækkevidde ind. Efter 2 træk eksploderer den og sender nærliggende enheder til vejrs.",
    "Melee attack that briefly turns nearby enemies to stone. If missed, the caster falls over.":
        "Nærkampsangreb, der kortvarigt forvandler nærliggende fjender til sten. Ved bom falder kasteren omkuld.",
    "Melee attack that deals more damage and knockback the farther the caster travels between swings. If missed, the caster falls over.":
        "Nærkampsangreb, der giver mere skade og tilbageslag, jo længere kasteren bevæger sig mellem slagene. Ved bom falder kasteren omkuld.",
    "Melee attack that forms a Crystal on impact. If missed, caster falls over. On cast, your Crystals become Cold, slowing and damaging nearby enemy units over time.":
        "Nærkampsangreb, der danner en krystal ved træf. Ved bom falder kasteren omkuld. Ved kast bliver dine krystaller kolde og bremser og skader nærliggende fjender over tid.",
    "Melee attack that imprisons units in a tree, preventing all damage and spellcasting. Tree will fall away from its caster. If missed, the caster falls over.":
        "Nærkampsangreb, der fanger enheder i et træ, så de hverken kan tage skade eller kaste besværgelser. Træet vælter væk fra kasteren. Ved bom falder kasteren omkuld.",
    "Melee attack that increases damage and knockback with each successful hit. If missed, the caster falls over and is launched backwards.":
        "Nærkampsangreb, der giver mere skade og tilbageslag for hvert træf. Ved bom falder kasteren omkuld og slynges bagud.",
    "Melee attack that launches nearby units into the air. If missed, the caster falls over.":
        "Nærkampsangreb, der sender nærliggende enheder til vejrs. Ved bom falder kasteren omkuld.",
    "Melee attack that rewinds the position of affected wizards. Damage is dealt based on distance from position when initially hit. If missed, the caster falls over.":
        "Nærkampsangreb, der spoler de ramte troldmænds position tilbage. Skaden afhænger af afstanden til stedet, hvor de blev ramt. Ved bom falder kasteren omkuld.",
    "Melee attack that shackles a unit to a ball and chain. If missed, the caster falls over.":
        "Nærkampsangreb, der lænker en enhed til en kugle med kæde. Ved bom falder kasteren omkuld.",
    "Melee attack with low knockback that deals damage over time. If missed, the caster falls over.":
        "Nærkampsangreb med lavt tilbageslag, der giver skade over tid. Ved bom falder kasteren omkuld.",
    "Metal star that can bounce to a nearby second target. Can hit caster-owned units.":
        "Metalstjerne, der kan hoppe videre til et mål mere i nærheden. Kan ramme kasterens egne enheder.",
    "Returns your wizard to their current location and health after 3 seconds, dealing damage and knockback along the way.":
        "Sender din troldmand tilbage til nuværende sted og liv efter 3 sekunder og giver skade og tilbageslag på vejen.",
    "Rock golem that summons on contact and chases after the unit it hit last.": "Stengolem, der fremkaldes ved kontakt og jagter den enhed, den sidst ramte.",
    "Rocket that accelerates through units, increasing its damage and knockback with each hit.":
        "Raket, der accelererer gennem enheder og giver mere skade og tilbageslag for hvert træf.",
    "Sea urchin that attaches itself to a unit. After 4 seconds, it latches to the next nearest unit, pulling it and the attached unit together, dealing damage on collision.":
        "Søpindsvin, der hænger fast på en enhed. Efter 4 sekunder griber det fat i den næste nærmeste enhed og trækker de to sammen med skade ved sammenstødet.",
    "Shield that grows as it absorbs spells, then explodes forward with proportional damage and knockback.":
        "Skjold, der vokser, mens det opsluger besværgelser, og derefter eksploderer fremad med tilsvarende skade og tilbageslag.",
    "Short dash that can be reactivated for a very long dash that pulls contacted units with it.":
        "Kort spurt, der kan genaktiveres til et meget langt spurt, som trækker de enheder, den rører, med.",
    "Short dash that can be reactivated to jump, dealing damage upon landing.": "Kort spurt, der kan genaktiveres til et hop med skade ved landing.",
    "Short leap that deals high damage in front of caster upon landing.": "Kort spring med høj skade foran kasteren ved landing.",
    "Short leap that leaves behind a trap which can steal control of a non-player unit if caught. Can be reactivated to toss unit, dealing damage on impact.":
        "Kort spring, der efterlader en fælde, som kan overtage en fanget computerstyret enhed. Genaktivér for at kaste enheden med skade ved træf.",
    "Short range leash that when landed successfully will pull an enemy toward caster. If missed, the caster is pulled to the location.":
        "Line med kort rækkevidde, der ved træf trækker en fjende hen til kasteren. Ved bom trækkes kasteren hen til stedet.",
    "Short range teleport that resets velocity and primary cooldown. Can be reactivated to return to casting point.":
        "Teleport med kort rækkevidde, der nulstiller fart og primær nedkøling. Genaktivér for at vende tilbage til kastestedet.",
    "Small fireball that can be activated up to 4 times in a row. Cooldown increases with each activation.":
        "Lille ildkugle, der kan aktiveres op til 4 gange i træk. Nedkølingen stiger for hver aktivering.",
    "Summons a chameleon that copies the last spell casted by target wizard. That wizard is slowed and the caster becomes invisible briefly. Reactivate to cast the copied spell.":
        "Fremkalder en kamæleon, der kopierer mål-troldmandens seneste besværgelse. Troldmanden bremses, og kasteren bliver kortvarigt usynlig. Genaktivér for at kaste den kopierede besværgelse.",
    "Summons a Crystal below the caster, launching them forward. On reactivation, the caster is pulled on a sled to their newest Crystal. On cast, your Crystals become Feral, following the nearest enemy unit.":
        "Fremkalder en krystal under kasteren, der sender kasteren fremad. Ved genaktivering trækkes kasteren på en slæde hen til sin nyeste krystal. Ved kast bliver dine krystaller vilde og følger den nærmeste fjende.",
    "Summons a Crystal that protects the caster until it’s destroyed or changes form. On cast, your Crystals become Cryogenic, preserving the first spell that damages them. Preserved spells can be picked up and used by the caster.":
        "Fremkalder en krystal, der beskytter kasteren, indtil den ødelægges eller skifter form. Ved kast bliver dine krystaller kryogene og fryser den første besværgelse, der skader dem. Frosne besværgelser kan samles op og bruges af kasteren.",
    "Summons a katana that stores all damage the caster deals for the next 5 seconds. The caster then jumps between all damaged units, dealing that damage a second time and applying the caster's melee spell.":
        "Fremkalder en katana, der opsamler al skade, kasteren giver de næste 5 sekunder. Derefter springer kasteren mellem alle ramte enheder, giver skaden en gang til og bruger sin nærkampsbesværgelse på dem.",
    "Summons an orb of fire that launches a cone of fireballs. If hit with a spell, it can be destroyed.":
        "Fremkalder en ildkugle, der affyrer en kegle af ildkugler. Den kan ødelægges, hvis den rammes af en besværgelse.",
    "Summons orbiting metal shields for 2 seconds. If damage would be taken, a shield is hurled at the source of that damage, chaining them to the caster and preventing all damage from that source for 5 seconds.":
        "Fremkalder kredsende metalskjolde i 2 sekunder. Hvis du ville tage skade, slynges et skjold mod kilden, lænker den til kasteren og blokerer al skade fra den i 5 sekunder.",
    "Summons puppet strings that delay all knockback and slow the target. All accumulated knockback is then released at once with a 30% bonus.":
        "Fremkalder marionettråde, der udskyder alt tilbageslag og bremser målet. Alt opsamlet tilbageslag udløses derefter på én gang med 30 % ekstra.",
    "Torrent of water that deals minor damage and minor knockback, but slows enemies briefly.":
        "Vandstrøm med lille skade og lille tilbageslag, men den bremser fjender kortvarigt.",
    "Torrent of water that splits into 7 parts, each part dealing half damage.": "Vandstrøm, der deler sig i 7 dele, som hver giver halv skade.",
    "Tosses a slow-moving, homing turtle armed with your melee spell.": "Kaster en langsom, målsøgende skildpadde bevæbnet med din nærkampsbesværgelse.",
    "Very thin, long range, fast moving skillshot with a huge area of effect and knockback.":
        "Meget smalt, hurtigt skud med lang rækkevidde, stort virkningsområde og tilbageslag.",
    "Vine that links to a unit or obstacle. If reactivated, caster accelerates towards its target, dealing damage and knockback based on speed of impact.":
        "Ranke, der hægter sig på en enhed eller forhindring. Ved genaktivering accelererer kasteren mod målet med skade og tilbageslag efter farten ved sammenstødet.",
    "Worm that teleports units and spells between its ends. Can be closed if reactivated.":
        "Orm, der teleporterer enheder og besværgelser mellem sine ender. Kan lukkes ved genaktivering.",
    "Short range teleport that resets velocity and primary cooldown.": "Teleport med kort rækkevidde, der nulstiller fart og primær nedkøling.",

    # --- Spell, element, stage and mode names (GameUtility.AddSpaces of enum values) ---
    "Air": "Luft", "Earth": "Jord", "Water": "Vand", "Ice": "Is", "Electric": "Elektrisk", "Metal": "Metal",
    "Steam": "Damp", "Sand": "Sand",
    "Airship": "Luftskib", "Berg": "Isbjerg", "Bridges": "Broer", "Compound": "Lejren", "Islands": "Øer",
    "Pit": "Hullet", "Plates": "Pladerne", "Ruins": "Ruinerne", "Shrine": "Helligdommen", "Sports": "Sport",
    "Tower": "Tårnet", "Village": "Landsbyen", "Volcano": "Vulkanen", "Coffin": "Kisten",
    "Classic": "Klassisk", "Draft": "Udvælgelse", "Less Random": "Mindre tilfældig", "Mirror Select": "Spejlvalg",
    "Random 7": "Tilfældige 7", "Random 7 Mirror": "Tilfældige 7, spejl",
    "Fireball": "Ildkugle", "Flame Leap": "Flammespring", "Flame Leash": "Flammeline", "Ignite": "Antænd",
    "Pillar Of Fire": "Ildsøjle", "Scorch": "Svid", "Spitfire": "Ildspyer", "Spark": "Gnist",
    "Bull Rush": "Tyrestorm", "Boomerang": "Boomerang", "Rock Block": "Stenblok", "Rockshot": "Stenskud",
    "Pet Rock": "Kæledyrssten", "Petrify": "Forsten", "Earth Tomb": "Jordgrav", "Fissure": "Revne",
    "Geyser": "Gejser", "Flash Flood": "Lynflod", "Water Cannon": "Vandkanon", "Tsunami": "Tsunami",
    "Bubble Breaker": "Bobleknuser", "Tonic": "Tonic", "Urchain": "Søpindsvin", "Seven Tears": "Syv tårer",
    "Gust": "Vindstød", "Jet Stream": "Jetstrøm", "Vacuum": "Vakuum", "Deflect": "Afbøj", "Push": "Skub",
    "Cy Clone": "Cy-klon", "Decoy": "Lokkedue", "Somer Assault": "Saltoangreb", "Sustain": "Udhold",
    "Chain Lightning": "Kædelyn", "Discharge": "Afladning", "Static": "Statisk", "Lightning Bug": "Ildflue",
    "Capacitor": "Kondensator", "Reflex": "Refleks", "Tetherball": "Tøjrbold",
    "Snowball": "Snebold", "Ice Hook": "Iskrog", "Ice Pack": "Ispose", "Cold Fusion": "Kold fusion",
    "Cold Shoulder": "Kold skulder", "Brrage": "Brrr-byge", "Preserve": "Bevar", "Suspend": "Svæv",
    "North Pull": "Nordtræk", "Sled Push": "Slædeskub",
    "Frog Of Life": "Livets frø", "Hinder": "Hindr", "Sapshot": "Saftskud", "Tow Vine": "Slæberanke",
    "Two Round Snake": "Torundsslange", "Wormhole": "Ormehul", "Steal Trap": "Tyvefælde",
    "Bombshell": "Bombe", "Chainmail": "Ringbrynje", "Glaive": "Glaive", "Rocket": "Raket", "Vanguard": "Fortrop",
    "Double Strike": "Dobbeltslag", "Sunder": "Knus", "Hot Swap": "Hurtigbyt", "Echo": "Ekko", "Relapse": "Tilbagefald",
    "Rewind": "Spol tilbage", "Time Bomb": "Tidsbombe", "Chameleon": "Kamæleon", "Backup": "Backup",
    "Writer's Quill": "Skribentens fjerpen", "2 Round Snake": "Torundsslange",

    # --- Batch 2: settings, stage/mode descriptions, lobby messages ---
    "1v1 mode can only be played as 1v1 teams.": "1v1-tilstand kan kun spilles som 1v1-hold.",
    "3 sets of 7 random spells are available to pick at the beginning of the match. This mode can only be played as a team 1v1.":
        "3 sæt med 7 tilfældige besværgelser kan vælges i starten af kampen. Denne tilstand kan kun spilles som 1v1 på hold.",
    "A 3-pointed island with damaging spikes in the center.": "En trekantet ø med skadelige pigge i midten.",
    "A bouncy mushroom in a medium sized arena surrounded by damaging murky water and walls.":
        "En hoppende svamp i en mellemstor arena omgivet af skadeligt mudret vand og mure.",
    "A little better looking than fast.": "Lidt pænere end Hurtig.",
    "A little better looking than fastest.": "Lidt pænere end Hurtigst.",
    "A little better looking than simple.": "Lidt pænere end Simpel.",
    "A new stage is selected randomly after each round.": "En ny bane vælges tilfældigt efter hver runde.",
    "A round arena that sinks concentrically and is surrounded by rotating walls.": "En rund arena, der synker ring for ring og er omgivet af roterende mure.",
    "A small enclosed village with damaging spikes throughout and a river down the center.":
        "En lille indhegnet landsby med skadelige pigge overalt og en flod gennem midten.",
    "A tower in a steam pool surrounded by a ring of land. Four bridges provide limited access to the top.":
        "Et tårn i en dampende sø omgivet af en ring af land. Fire broer giver begrænset adgang til toppen.",
    "All 7 spells are assigned randomly at the beginning of the match.": "Alle 7 besværgelser tildeles tilfældigt i starten af kampen.",
    "All 7 spells are assigned randomly at the beginning of the match. This mode can only be played with even teams, as the same spells are given to each side.":
        "Alle 7 besværgelser tildeles tilfældigt i starten af kampen. Denne tilstand kan kun spilles med lige store hold, da begge sider får de samme besværgelser.",
    "Allows 5+ Xbox controllers to be used, but Steam Controller and Steam Link will not work.":
        "Tillader 5+ Xbox-controllere, men Steam Controller og Steam Link virker ikke.",
    "Cannot ban all elements.": "Du kan ikke udelukke alle elementer.",
    "Cannot force more than 4 elements to be included.": "Du kan ikke tvinge mere end 4 elementer med.",
    "Classic rules. The way MageQuit was meant to be enjoyed. Great for casual matches with friends.":
        "Klassiske regler. Sådan skal MageQuit nydes. Godt til hyggekampe med venner.",
    "Code invalid.": "Ugyldig kode.",
    "Complete the Tutorial to unlock keyboard remapping.": "Gennemfør øvelsen for at kunne ændre tastaturet.",
    "Connection with the matchmaker has been lost": "Forbindelsen til matchmakeren er tabt",
    "Cursed game mode #1. Sand spells only, Coffin only. Play as teams to have a worse time.":
        "Forbandet spiltilstand #1. Kun sandbesværgelser, kun Kisten. Spil på hold for at få det endnu værre.",
    "Cursed game mode #2. Steam spells only, Sports only. Play as teams to have a puck.":
        "Forbandet spiltilstand #2. Kun dampbesværgelser, kun Sport. Spil på hold for at få en puck.",
    "Cursed game mode #3. Nature spells only, Pit only. Did your mom say you could play one more game? This is the mode for you.":
        "Forbandet spiltilstand #3. Kun naturbesværgelser, kun Hullet. Sagde din mor, at du måtte spille ét spil mere? Så er det denne tilstand.",
    "Customize your keyboard controls here. Choose between Mouse and WASD for movement and remap your spell and curve buttons.":
        "Tilpas din tastaturstyring her. Vælg mellem mus og WASD til bevægelse, og flyt dine besværgelses- og kurveknapper.",
    "Disables detailed logging. Recommended if you really need the performance gains.":
        "Slår detaljeret logning fra. Anbefales, hvis du virkelig har brug for ydelsen.",
    "Each wizard or team gets their own island. Islands sink randomly over time until there is one left.":
        "Hver troldmand eller hvert hold får sin egen ø. Øerne synker tilfældigt, indtil der er én tilbage.",
    "Enables detailed logging to help diagnose issues. May hurt performance a tiny bit.":
        "Slår detaljeret logning til for at finde fejl. Kan koste en smule ydelse.",
    "Exclusive Full Screen": "Eksklusiv fuld skærm",
    "Flying ship that separates wizards into small groups. Defeat the wizard in your room to advance to the next.":
        "Flyvende skib, der deler troldmændene i små grupper. Besejr troldmanden i dit rum for at komme videre til det næste.",
    "For the non-epileptic.": "For ikke-epileptikere.",
    "Full Screen Window": "Fuldskærmsvindue",
    "Games DO NOT end early even if there is a clear winner.": "Spillet slutter IKKE før tid, selvom der er en klar vinder.",
    "Games end once there is a clear winner.": "Spillet slutter, så snart der er en klar vinder.",
    "Hold left or right mouse button before casting to curve spells.": "Hold venstre eller højre museknap nede før kastet for at kurve besværgelser.",
    "Hold left or right trigger before casting to curve spells.": "Hold venstre eller højre aftrækker nede før kastet for at kurve besværgelser.",
    "Join Queue": "Stil dig i kø",
    "Large arena with obstacles to hide behind.": "Stor arena med forhindringer at gemme sig bag.",
    "Large enclosed arena with a pit in the center.": "Stor indhegnet arena med et hul i midten.",
    "Less chance. More sweat. Ideal for tournaments and competitive play.": "Mindre held. Mere sved. Ideel til turneringer og konkurrencespil.",
    "MageQuit is full screen and borderless, and can be switched out of easily without minimizing it.":
        "MageQuit kører i fuld skærm uden kant, og du kan nemt skifte væk uden at minimere.",
    "MageQuit is full screen and borderless, but can't be switched out of unless minimized. Can help improve game performance.":
        "MageQuit kører i fuld skærm uden kant, men du kan kun skifte væk ved at minimere. Kan forbedre ydelsen.",
    "MageQuit is running in a maximized window.": "MageQuit kører i et maksimeret vindue.",
    "MageQuit is windowed.": "MageQuit kører i et vindue.",
    "MageQuit will attempt to create the fairest possible match. Only available in Online.":
        "MageQuit prøver at lave den mest retfærdige kamp. Kun online.",
    "Maximized Window": "Maksimeret vindue",
    "Medium sized arena surrounded by damaging snow.": "Mellemstor arena omgivet af skadelig sne.",
    "Mirror mode can only be played with even teams.": "Spejl-tilstand kan kun spilles med lige store hold.",
    "must not lose next round": "må ikke tabe næste runde",
    "must sweep next round": "skal vinde næste runde rent",
    "must win next round": "skal vinde næste runde",
    "NEW SPOILS UNLOCKED": "NYT BYTTE LÅST OP",
    "Nice looking but not as pretty as fantastic.": "Flot, men ikke så pænt som Fantastisk.",
    "No drafting. Great for fast, even matches. Requires all teams to be the same size AND FOR EVERYONE TO KNOW ALL OF THE SPELLS ALREADY.":
        "Ingen udvælgelse. Godt til hurtige, jævne kampe. Kræver, at alle hold er lige store, OG AT ALLE ALLEREDE KENDER ALLE BESVÆRGELSERNE.",
    "No Steam Account Found": "Ingen Steam-konto fundet",
    "One team wouldn't be very fun.": "Ét hold ville ikke være særlig sjovt.",
    "Oops All Wormholes": "Ups, kun ormehuller",
    "Players need to be all on teams or all on no teams.": "Enten skal alle spillere være på hold, eller også skal ingen være det.",
    "Please add more players or bots to play.": "Tilføj flere spillere eller botter for at spille.",
    "Practice spells, experiment with combos, and improve your aim without all the pressure of a real game.":
        "Øv besværgelser, eksperimentér med kombinationer, og bliv bedre til at sigte uden presset fra et rigtigt spil.",
    "Raised hexagon arena with 2 open ends. Instant death if you fall off. Team mode adds a wind wall that can be pushed to win.":
        "Hævet sekskantet arena med 2 åbne ender. Falder du af, dør du med det samme. På hold er der en vindmur, der kan skubbes for at vinde.",
    "Required for Steam Controller and Steam Link to work, but limits Xbox (and Steam) controllers to a maximum of 4.":
        "Kræves for at Steam Controller og Steam Link virker, men begrænser Xbox- (og Steam-) controllere til højst 4.",
    "Round": "Runde",
    "Same as Classic Draft, except the first 2 spells are drafted before the first round. Great for competitive play.":
        "Som Klassisk udvælgelse, men de første 2 besværgelser vælges før første runde. Godt til konkurrencespil.",
    "Same as Random, but not as random. You won't play the same stage twice unless there are more than 9 rounds. Volcano will not erupt randomly and Airship propellers hit to center.":
        "Som Tilfældig, men ikke helt så tilfældig. Du spiller ikke samme bane to gange, medmindre der er mere end 9 runder. Vulkanen går ikke i udbrud tilfældigt, og Luftskibets propeller slår ind mod midten.",
    "Second Spell Draft": "Anden besværgelsesudvælgelse",
    "SIGN UP": "TILMELD",
    "Small arena with an active volcano in the center. Sacrifice an enemy to the volcano for a massive eruption in your favor.":
        "Lille arena med en aktiv vulkan i midten. Ofr en fjende til vulkanen for et kæmpe udbrud til din fordel.",
    "Small round arena with no obstructions, surrounded by rising lava.": "Lille rund arena uden forhindringer, omgivet af stigende lava.",
    "Sound volume level.": "Lydstyrke for effekter.",
    "Sports arena with 2 or 3 goals. Must be played with teams to use the puck of death. Score on a team to obliterate them.":
        "Sportsarena med 2 eller 3 mål. Skal spilles på hold for at bruge dødspucken. Scor på et hold for at udslette det.",
    "Sports Only": "Kun Sport",
    "Standard": "Standard",
    "The game will run at a maximum of 30 frames per second.": "Spillet kører med højst 30 billeder i sekundet.",
    "The game will run at a maximum of 60 frames per second.": "Spillet kører med højst 60 billeder i sekundet.",
    "The game will run at a maximum of 75 frames per second.": "Spillet kører med højst 75 billeder i sekundet.",
    "The game will run at a maximum of 90 frames per second.": "Spillet kører med højst 90 billeder i sekundet.",
    "The game will run at a maximum of 120 frames per second.": "Spillet kører med højst 120 billeder i sekundet.",
    "The game will run at a maximum of 144 frames per second.": "Spillet kører med højst 144 billeder i sekundet.",
    "The game will run at a maximum of 165 frames per second.": "Spillet kører med højst 165 billeder i sekundet.",
    "The game will run at a maximum of 240 frames per second.": "Spillet kører med højst 240 billeder i sekundet.",
    "The game will run at a maximum of 360 frames per second.": "Spillet kører med højst 360 billeder i sekundet.",
    "Unable to connect to matchmaking server.\n": "Kan ikke forbinde til matchmaking-serveren.\n",
    "User not logged in": "Brugeren er ikke logget ind",
    "You cannot play online with Xbox Silver.": "Du kan ikke spille online med Xbox Silver.",
    "You were disconnected :(": "Forbindelsen blev afbrudt :(",
    "You were disconnected from Xbox Live.": "Forbindelsen til Xbox Live blev afbrudt.",
    "You will join at the end of the round!": "Du kommer med, når runden er slut!",
    "(left early)": "(gik før tid)",
    "Accept Invite": "Acceptér invitation",
    "Allow Join": "Tillad deltagelse",
    "Assigning Spells": "Tildeler besværgelser",
    "Backhand Spell": "Baghåndsbesværgelse",
    "Connecting": "Forbinder",
    "Down": "Ned",
    "Final Score": "Slutresultat",
    "First Win of the Day": "Dagens første sejr",
    "In Spectate Mode": "Ser med som tilskuer",
    "Invalid Teams": "Ugyldige hold",
    "Invited": "Inviteret",
    "Join Game": "Deltag i spil",
    "Joining Game": "Deltager i spil",
    "Loading": "Indlæser",
    "Main Menu": "Hovedmenu",
    "Mercy Bonus": "Nådebonus",
    "Mode is Team 1v1 Only": "Kun 1v1 på hold i denne tilstand",
    "Not Enough Elements": "Ikke nok elementer",
    "OBJECTIVE:  Move the wind wall by pushing as a team!": "MÅL:  Flyt vindmuren ved at skubbe sammen som hold!",
    "OBJECTIVE:  Use spells to knock the puck into your opponent's goal!": "MÅL:  Brug besværgelser til at skyde pucken i modstanderens mål!",
    "Online Lobby": "Online-lobby",
    "Our audio engine (FMOD) was unable to initialize. This can happen if things like Realtek Audio or Sonic Sound Studio are running. Try disabling them.":
        "Vores lydmotor (FMOD) kunne ikke starte. Det kan ske, hvis f.eks. Realtek Audio eller Sonic Sound Studio kører. Prøv at slå dem fra.",
    "Secondary Spell": "Sekundær besværgelse",
    "Send": "Send",
    "Someone": "Nogen",
    "Too Many Elements Banned": "For mange elementer udelukket",
    "Too Many Elements Set": "For mange elementer valgt",
    "Winner": "Vinder",
    "XB Live Down": "Xbox Live er nede",
}

# Text built at runtime. kind "regex": $1.. substitutions; kind "split": XUnity translates each group separately.
REGEX = [
    ("regex", r"^Level (\d+)$", "Niveau $1"),
    ("regex", r"^Level (\d+) Required\.$", "Kræver niveau $1."),
    ("regex", r"^Bots will all be (?:Level|Niveau) (\d+) of 10\.$", "Alle botter er på niveau $1 af 10."),
    ("regex", r"^1 bot will be added to the match\.$", "1 bot bliver tilføjet til kampen."),
    ("regex", r"^(\d+) bots will be added to the match\.$", "$1 botter bliver tilføjet til kampen."),
    ("regex", r"^Round (\d+) of (\d+)$", "Runde $1 af $2"),
    ("regex", r"^Round (\d+) Recap$", "Opsummering af runde $1"),
    ("regex", r"^Round (\d+)$", "Runde $1"),
    ("regex", r"^Showdown (\d+) of (\d+)$", "Opgør $1 af $2"),
    ("regex", r"^Showdown (\d+)$", "Opgør $1"),
    ("regex", r"^(\d+) of (\d+)$", "$1 af $2"),
    ("regex", r"^(\d+) GEMS$", "$1 ÆDELSTEN"),
    ("regex", r"^(\d+) Kills?$", "$1 drab"),
    ("regex", r"^(\d+) Team Kills?$", "$1 holddrab"),
    ("regex", r"^(\d+) Team Kills? / (\d+)$", "$1 holddrab / $2"),
    ("regex", r"^Party of (\d+) \(\+(\d+)%\)$", "Gruppe på $1 (+$2%)"),
    ("regex", r"^(\d+) XP$", "$1 XP"),
    ("regex", r"^(.+) has joined the battle!$", "$1 er med i kampen!"),
    ("regex", r"^(.+) has left the battle!$", "$1 har forladt kampen!"),
    ("regex", r"^(.+) has forfeited!$", "$1 har givet op!"),
    ("regex", r"^Player (\d+)$", "Spiller $1"),
    ("split", r"^(?<el>[A-Za-z ]+) WILL be available this game\.$", "${el} KAN vælges i dette spil."),
    ("split", r"^(?<el>[A-Za-z ]+) will NOT be available this game\.$", "${el} kan IKKE vælges i dette spil."),
    ("split", r"^(?<el>[A-Za-z ]+) COULD be available this game\.$", "${el} KAN MÅSKE vælges i dette spil."),
]

# Never shown on their own: debug output, internal identifiers, fragments covered by REGEX above.
DROP = {
    "33: result = ", "asdfasdfadsfc", "ASDghjas has joined the battle!", "brettpennings vs Pkfyre",
    "This is a spell description.", "Type of the effect", "The speed of the projectile", "SRDebugger {0}",
    "Option A", "Relative Velocity", "Relative X Velocity", "Velocity Magnitude", "WHATTT", "Bot 1",
    "Team Chad", "Sep 8, 2019  |  1 PM EST", "magequit.com/igl", "magequit.com/score", "spellbook.magequit.com",
    "Next Effect", "Previous Effect", "Target Mask", "TStart", "Use UserId.", "ViewID {0} {1}{2}", "3d text",
    "AutoFade", "Billboard_", "CLOSE PLAY MODAL: ", "OPEN PLAY MODAL: ", "INIT GAME PREFERENCES MENU", "INITIALIZED",
    "LevelRequired", "LogStats", "Prop", "Remapper", "SEND VIEW UPDATE ", "Scores submitted!: ", "default prefs = ",
    "loaded prefs = ", "start match: ", "submit scores, attempt #", "match updated!", "FlameLeap", "FToA", "Id",
    "Somer Assault Flip", "Spell 360", "----------- KEYS: ", "Last joystick ", "Keypad ", "Alpha ", "Comma", "Period",
    "Ball Speed ", "Party of ", "Bot ", "Level ", "and", "or", "in the", "out some", "PRESS", "N/A",
    "17m 30s", "1920x1080 60Hz", "199999 XP", "25 GEMS", "Bronze III", "6 Kills", "2 of 5", "Round 3", "Level 1",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "chad.pennings", "fabioescolastic", "brettpennings", "BowlcutStudios", "EmJov",
    "HP", "II", "III", "IV", "LB", "LS", "LT", "RB", "RS", "RT", "DIVIDE BY ZERO",
    # Inspector tooltips, third-party and network internals
    "A projectile will be moved to the target (any object)", "Allows you to smoothly activate / deactivate effects which have an indefinite lifetime",
    "Delay before deactivating effect. (For example, after effect, some particles must have time to disappear).",
    "Delay before deleting effect. (For example, after effect, some particles must have time to disappear).",
    "Get the position of the movement of the motion vector, and not to follow to the target.",
    "Motion vector for the projectile (eg Vector3.Forward)", "Should the projectile have move to the target, until the target not reaches?",
    'The radius of the "Area Of Damage (AOE)"', "node trace", "OnClick", "OnPickedUp", "OnPress", "OnPressRight", "OnRelease",
    "TCP Disconnect", "Use RequestForPickupItems(PhotonMessageInfo msgInfo) with corrected typing instead.",
    '"  \r\nHold any mouse button that would move the camera', ".bin", "Attempting to Re-Init controller states on start",
    "Change environment", "ChatInput", "Columns", "CurveLeftAndCast", "CurveRightAndCast", "Effect worked only on Unity4!",
    "Error calling OpAuthenticate! Did not work. Check log output, AuthValues and if you're connected.", "EventGamesRequired",
    "Exchanging encrpytion keys is done internally in the lib now. Don't expect this operation-result.", "Flying Forward",
    "Google GVR Listener", "HORIPAD mini4", "Image Effects/Sonic Ether/SE Natural Bloom and Dirty Lens", "Katana Summon",
    "match already ended!", "Mine", "MoveAndCast", "MovementSpell", "new round", "nintendo switch",
    "No longer used, cause random matchmaking is no longer a process.", "not logged in so don't attempt to unlock achievement.",
    "Not waiting on any clients to join", "on master", "OpAuthenticate() failed. When you want Custom Authentication encryption is mandatory.",
    "OpGetGameList not sent. Lobby cannot be null.", "OpGetGameList not sent. LobbyType must be SqlLobby.",
    "OpSetPropertiesOfActor not sent. ActorNr must be > 0 and actorProperties != null.", "Panels", 'Prefab name is "',
    "PunSupportLogger", "RenderTextureCamera", "Resonance Audio Listener", "Scene", "Showdown End", "Skins", "SkinSetId",
    "SkinSets", "SkinTypeId", "Spell Channel", "switch pro controller", "TCP routing was removed after becoming obsolete.",
    "Turn", "UI Elements", "Use InvalidOperation.", "Use PropertiesChanged now.", "Wardrobe Manager", "XInput",
    # Bot names
    "BAINT", "BIRB", "BOI", "BRUCE", "CAKEBABY", "CHANCE", "DADDY", "DUMBLE", "FUDGE", "GANDALF", "HARRY", "HERMIONE",
    "JAFAR", "MERLIN", "MUFFINS", "MUNCH", "PENNIN", "RON", "SLAB", "SNAPE",
}

DROP_PREFIX = ("The radius of the collider", "Distance flight of the projectile", "Whether to deactivate or destroy")


def main(path):
    data = json.load(open(path, encoding="utf-8"))
    strings = data["strings"]
    kept, dropped, filled = [], 0, 0
    for e in strings:
        en = e["en"]
        fragment = e.get("kind", "text") == "text" and (en != en.strip() and en.strip() == en.strip(" ")
                                                         and not en.endswith("\n"))
        if not e.get("edited") and (en in DROP or en.startswith(DROP_PREFIX) or fragment or (len(en.strip()) == 1 and en.strip().isalpha())
                                    or en.strip().startswith(("F1", "F2", "F3", "F4")) and len(en.strip()) == 2):
            dropped += 1
            continue
        if not e.get("da") and en in TEXT and not e.get("edited"):
            e["da"] = TEXT[en]
            e["status"] = "machine"
            filled += 1
        kept.append(e)
    have = {(e.get("kind", "text"), e["en"]) for e in kept}
    for kind, pattern, repl in REGEX:
        if (kind, pattern) not in have:
            kept.append({"en": pattern, "da": repl, "status": "machine", "kind": kind, "confidence": "high",
                         "sources": ["runtime"], "fonts": [], "uppercase_only": False, "note": "", "edited": False})
    data["strings"] = kept
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    missing = [e["en"] for e in kept if not e.get("da")]
    print(f"filled {filled}, dropped {dropped}, regex {len(REGEX)}, still untranslated {len(missing)}")
    for m in missing:
        print("  ", repr(m))


if __name__ == "__main__":
    main(sys.argv[1])
