using System.Globalization;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace MageQuitTranslator.Core;

/// <summary>translation/&lt;code&gt;/language.json</summary>
public sealed class LanguageInfo
{
    /// <summary>Language code used for folders and by XUnity.AutoTranslator, e.g. "da", "de", "pt-BR".</summary>
    [JsonPropertyName("code")] public string Code { get; set; } = "";
    /// <summary>English name, e.g. "Danish".</summary>
    [JsonPropertyName("name")] public string Name { get; set; } = "";
    /// <summary>Name in the language itself, e.g. "Dansk".</summary>
    [JsonPropertyName("nativeName")] public string NativeName { get; set; } = "";
    [JsonPropertyName("authors")] public List<string> Authors { get; set; } = [];
    [JsonPropertyName("notes")] public string Notes { get; set; } = "";

    public override string ToString() => $"{NativeName} ({Name})";

    static readonly Regex CodePattern = new(@"^[a-z]{2,3}(-[A-Z]{2}|-[A-Z][a-z]{3})?$");

    public static bool IsValidCode(string code) => CodePattern.IsMatch(code);

    /// <summary>Fills names from .NET's culture data when they are left empty.</summary>
    public static LanguageInfo Create(string code, string? name = null, string? nativeName = null)
    {
        if (!IsValidCode(code))
            throw new ArgumentException($"'{code}' is not a language code like 'de' or 'pt-BR'.");
        string? englishName = null, native = null;
        try
        {
            var culture = CultureInfo.GetCultureInfo(code);
            englishName = culture.EnglishName;
            native = culture.TextInfo.ToTitleCase(culture.NativeName);
        }
        catch (CultureNotFoundException)
        {
        }
        return new LanguageInfo
        {
            Code = code,
            Name = string.IsNullOrWhiteSpace(name) ? englishName ?? code : name,
            NativeName = string.IsNullOrWhiteSpace(nativeName) ? native ?? code : nativeName,
        };
    }
}

/// <summary>Everything for one language: the folder translation/&lt;code&gt;/ in the repo.</summary>
public sealed class LanguagePack
{
    public const string InfoFile = "language.json";
    public const string StringsFile = "strings.json";
    public const string LabelsFile = "labels.json";

    public LanguageInfo Info { get; set; } = new();
    public TranslationFile Strings { get; set; } = new();
    public LabelFile Labels { get; set; } = new();

    public string Code => Info.Code;

    public static LanguagePack Load(string dir) => new()
    {
        Info = Json.Read<LanguageInfo>(Path.Combine(dir, InfoFile)),
        Strings = TranslationFile.Load(Path.Combine(dir, StringsFile)),
        Labels = File.Exists(Path.Combine(dir, LabelsFile)) ? LabelFile.Load(Path.Combine(dir, LabelsFile)) : new(),
    };

    public static LanguagePack Parse(string info, string strings, string? labels) => new()
    {
        Info = Json.Parse<LanguageInfo>(info),
        Strings = TranslationFile.Parse(strings),
        Labels = labels == null ? new() : LabelFile.Parse(labels),
    };

    public void Save(string dir)
    {
        Json.WriteAtomic(Path.Combine(dir, InfoFile), Info);
        Strings.Save(Path.Combine(dir, StringsFile));
        Labels.Save(Path.Combine(dir, LabelsFile));
    }

    /// <summary>Writes the folder exactly as it should appear in translation/&lt;code&gt;/ in a pull request.</summary>
    public void ExportForPullRequest(string dir)
    {
        Directory.CreateDirectory(dir);
        Json.WriteAtomic(Path.Combine(dir, InfoFile), Info);
        Strings.ForExport().Save(Path.Combine(dir, StringsFile));
        Labels.ForExport().Save(Path.Combine(dir, LabelsFile));
    }

    /// <summary>A new, empty language with every string from <paramref name="source"/>.</summary>
    public static LanguagePack CreateFrom(LanguagePack source, LanguageInfo info) => new()
    {
        Info = info,
        Strings = source.Strings.ToTemplate(info.Code),
        Labels = source.Labels.ToTemplate(),
    };

    /// <summary>Merges a newer shipped version of this language into a working copy (user edits win).</summary>
    public void MergeShipped(LanguagePack shipped)
    {
        Info = shipped.Info;
        Strings.MergeShipped(shipped.Strings);
        Labels.MergeShipped(shipped.Labels);
    }

    public (int Total, int Reviewed, int Draft) Progress()
    {
        int total = Strings.Strings.Count, reviewed = 0, draft = 0;
        foreach (var e in Strings.Strings)
        {
            if (e.Status == "reviewed" && e.Text.Length > 0) reviewed++;
            else if (e.Text.Length > 0) draft++;
        }
        return (total, reviewed, draft);
    }
}

/// <summary>
/// Which characters each game font can display (fonts.json, generated by tools/fonts/font_coverage.py),
/// so translators are warned about letters that would show up as boxes in game.
/// </summary>
public sealed class FontCoverage
{
    public sealed class FontInfo
    {
        [JsonPropertyName("chars")] public string Chars { get; set; } = "";
        [JsonPropertyName("uppercaseOnly")] public bool UppercaseOnly { get; set; }
    }

    [JsonPropertyName("fonts")] public Dictionary<string, FontInfo> Fonts { get; set; } = [];

    readonly Dictionary<string, HashSet<int>> _sets = [];

    public static FontCoverage Load(string path) => File.Exists(path) ? Json.Read<FontCoverage>(path) : new();
    public static FontCoverage Parse(string json) => Json.Parse<FontCoverage>(json);

    internal static bool IsUppercaseOnlyFont(string font) => font is "MageQuitHeaderThin" or "soupofjustice";

    /// <summary>Characters in <paramref name="text"/> that one of <paramref name="fonts"/> cannot display.</summary>
    public string MissingChars(string text, IEnumerable<string> fonts, bool uppercase = false)
    {
        if (uppercase)
            text = text.ToUpperInvariant();
        var missing = new SortedSet<char>();
        foreach (var font in fonts)
        {
            if (!Fonts.TryGetValue(font, out var info))
                continue;
            if (!_sets.TryGetValue(font, out var set))
                _sets[font] = set = [.. info.Chars.Select(c => (int)c)];
            foreach (var c in text)
                if (c >= 0x20 && !char.IsWhiteSpace(c) && !set.Contains(c))
                    missing.Add(c);
        }
        return new string([.. missing]);
    }
}
