using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MageQuitTranslator.Core;

/// <summary>One translatable string. Mirrors an entry in translation/&lt;code&gt;/strings.json.</summary>
public sealed class TranslationEntry
{
    /// <summary>English source text, or a regex pattern when <see cref="Kind"/> is "regex"/"split".</summary>
    [JsonPropertyName("en")] public string En { get; set; } = "";
    /// <summary>The translation.</summary>
    [JsonPropertyName("text")] public string Text { get; set; } = "";
    /// <summary>"new" (untranslated), "machine" (draft, needs review) or "reviewed".</summary>
    [JsonPropertyName("status")] public string Status { get; set; } = "new";
    /// <summary>"text" for exact matches, "regex" for XUnity regex entries (En is the pattern, Text the replacement),
    /// "split" for XUnity splitter regexes whose groups are translated separately.</summary>
    [JsonPropertyName("kind")] public string Kind { get; set; } = "text";
    /// <summary>How sure we are the string is shown in game: high, enum, low, captured.</summary>
    [JsonPropertyName("confidence")] public string Confidence { get; set; } = "high";
    [JsonPropertyName("sources")] public List<string> Sources { get; set; } = [];
    [JsonPropertyName("fonts")] public List<string> Fonts { get; set; } = [];
    [JsonPropertyName("uppercase_only")] public bool UppercaseOnly { get; set; }
    [JsonPropertyName("note")] public string Note { get; set; } = "";
    /// <summary>Set when the user changed this entry in the app; such entries survive mod updates.
    /// Local only: cleared when a language is exported for a pull request.</summary>
    [JsonPropertyName("edited")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool Edited { get; set; }

    [JsonIgnore] public bool IsPattern => Kind is "regex" or "split";
    [JsonIgnore] internal string Key => Kind + "\0" + En;
}

public sealed class TranslationFile
{
    [JsonPropertyName("language")] public string Language { get; set; } = "";
    [JsonPropertyName("strings")] public List<TranslationEntry> Strings { get; set; } = [];

    public static TranslationFile Load(string path) => Json.Read<TranslationFile>(path);
    public static TranslationFile Parse(string json) => Json.Parse<TranslationFile>(json);
    public void Save(string path) => Json.WriteAtomic(path, this);

    /// <summary>
    /// Merges a newer shipped translation into this (the user's working copy): entries the user
    /// edited are kept, everything else takes the shipped version, and new strings are added.
    /// </summary>
    public void MergeShipped(TranslationFile shipped)
    {
        var mine = Strings.ToDictionary(e => e.Key);
        var result = new List<TranslationEntry>();
        foreach (var s in shipped.Strings)
        {
            if (mine.Remove(s.Key, out var m) && m.Edited)
                result.Add(m);
            else
                result.Add(s);
        }
        // Keep the user's own additions (captured or hand-added strings) that the shipped file lacks.
        result.AddRange(mine.Values.Where(m => m.Edited || m.Confidence == "captured"));
        Strings = result;
    }

    /// <summary>Every English string with no translations: the starting point for a new language.</summary>
    public TranslationFile ToTemplate(string code) => new()
    {
        Language = code,
        Strings = Strings.Select(e => new TranslationEntry
        {
            En = e.En, Kind = e.Kind, Confidence = e.Confidence, Sources = [.. e.Sources], Fonts = [.. e.Fonts],
            UppercaseOnly = e.UppercaseOnly,
            Note = e.IsPattern && e.Text.Length > 0 ? $"Text built by the game. Example from '{Language}': {e.Text}" : "",
        }).ToList(),
    };

    /// <summary>A copy suitable for sharing: local "edited" flags removed.</summary>
    public TranslationFile ForExport()
    {
        var copy = Json.Parse<TranslationFile>(Json.Serialize(this));
        foreach (var e in copy.Strings)
            e.Edited = false;
        return copy;
    }

    /// <summary>Writes the XUnity.AutoTranslator text file for all translated entries.</summary>
    public string ToXUnity()
    {
        var sb = new StringBuilder();
        sb.Append("// Generated by MageQuit Translator from strings.json. Edit translations in the Translator app.\n");
        foreach (var e in Strings)
        {
            if (string.IsNullOrWhiteSpace(e.Text))
                continue;
            var text = e.UppercaseOnly ? e.Text.ToUpperInvariant() : e.Text;
            if (e.IsPattern)
                sb.Append(e.Kind == "split" ? "sr:\"" : "r:\"").Append(Escape(e.En)).Append("\"=").Append(Escape(text)).Append('\n');
            else
                sb.Append(Escape(e.En)).Append('=').Append(Escape(text)).Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>Escapes text for XUnity's KEY=VALUE format (see TextHelper.ReadTranslationLineAndDecode).</summary>
    internal static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '=': sb.Append(@"\="); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                // "//" starts an inline comment and "%3D" is a legacy '=' encoding; break both up.
                case '/' when i + 1 < s.Length && s[i + 1] == '/': sb.Append(@"\u002F"); break;
                case '%' when i + 2 < s.Length && s[i + 1] == '3' && s[i + 2] == 'D': sb.Append(@"\u0025"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    /// <summary>
    /// Imports strings recorded by the plugin's capture mode (captured.tsv). Strings already
    /// known (as English or as a translation in any language) are skipped. Returns the number added.
    /// </summary>
    public int ImportCaptured(string tsvPath, IEnumerable<string>? otherTranslations = null)
    {
        var known = new HashSet<string>(Strings.Select(e => e.En));
        foreach (var e in Strings.Where(e => e.Text.Length > 0))
        {
            known.Add(e.Text);
            known.Add(e.Text.ToUpperInvariant());
        }
        if (otherTranslations != null)
            known.UnionWith(otherTranslations);
        var patterns = Strings.Where(e => e.IsPattern && e.En.Length > 0)
                              .Select(e => TryRegex(e.En)).OfType<System.Text.RegularExpressions.Regex>().ToList();
        int added = 0;
        foreach (var line in File.ReadLines(tsvPath, Encoding.UTF8).Skip(1))
        {
            var f = line.Split('\t');
            if (f.Length < 5)
                continue;
            var text = Unescape(f[0]);
            if (known.Contains(text) || IsNoise(text) || patterns.Any(r => r.IsMatch(text)))
                continue;
            known.Add(text);
            Strings.Add(new TranslationEntry
            {
                En = text,
                Confidence = "captured",
                Sources = [$"{f[2]}: {Unescape(f[3])}"],
                Fonts = string.IsNullOrEmpty(f[1]) ? [] : [f[1]],
                UppercaseOnly = FontCoverage.IsUppercaseOnlyFont(f[1]),
                Edited = true,
            });
            added++;
        }
        return added;
    }

    static System.Text.RegularExpressions.Regex? TryRegex(string pattern)
    {
        try { return new System.Text.RegularExpressions.Regex(pattern); }
        catch (ArgumentException) { return null; }
    }

    /// <summary>Numbers, single letters and the like are not worth translating.</summary>
    static bool IsNoise(string s) =>
        s.Trim().Length <= 1 || !s.Any(char.IsLetter) ||
        System.Text.RegularExpressions.Regex.IsMatch(s, @"^[\d\s.,:+\-/%xX]+[A-Za-z]{0,3}$");

    static string Unescape(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            if (s[i] == '\\' && i + 1 < s.Length)
            {
                var n = s[++i];
                sb.Append(n switch { 't' => '\t', 'n' => '\n', 'r' => '\r', _ => n });
            }
            else sb.Append(s[i]);
        }
        return sb.ToString();
    }
}

/// <summary>Shared JSON settings: readable output, real UTF-8 letters, LF line endings.</summary>
static class Json
{
    static readonly JsonSerializerOptions Options = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public static string Serialize<T>(T value) => JsonSerializer.Serialize(value, Options).Replace("\r\n", "\n");

    public static void WriteAtomic<T>(string path, T value)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        var tmp = path + ".tmp";
        File.WriteAllText(tmp, Serialize(value), new UTF8Encoding(false));
        File.Move(tmp, path, overwrite: true);
    }

    public static T Read<T>(string path) where T : new() => Parse<T>(File.ReadAllText(path, Encoding.UTF8));

    public static T Parse<T>(string json) where T : new() => JsonSerializer.Deserialize<T>(json, Options) ?? new T();
}
