using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MageQuitDA.Core;

/// <summary>One translatable string. Mirrors an entry in translation/strings.json.</summary>
public sealed class TranslationEntry
{
    /// <summary>English source text, or a regex pattern when <see cref="Kind"/> is "regex".</summary>
    [JsonPropertyName("en")] public string En { get; set; } = "";
    [JsonPropertyName("da")] public string Da { get; set; } = "";
    /// <summary>"new" (untranslated), "machine" (draft, needs review) or "reviewed".</summary>
    [JsonPropertyName("status")] public string Status { get; set; } = "new";
    /// <summary>"text" for exact matches, "regex" for XUnity regex entries (En is the pattern, Da the replacement),
    /// "split" for XUnity splitter regexes whose groups are translated separately.</summary>
    [JsonPropertyName("kind")] public string Kind { get; set; } = "text";
    /// <summary>How sure we are the string is shown in game: high, enum, low, captured.</summary>
    [JsonPropertyName("confidence")] public string Confidence { get; set; } = "high";
    [JsonPropertyName("sources")] public List<string> Sources { get; set; } = [];
    [JsonPropertyName("fonts")] public List<string> Fonts { get; set; } = [];
    [JsonPropertyName("uppercase_only")] public bool UppercaseOnly { get; set; }
    [JsonPropertyName("note")] public string Note { get; set; } = "";
    /// <summary>Set when the user changed this entry in the Manager; such entries survive mod updates.</summary>
    [JsonPropertyName("edited")] public bool Edited { get; set; }
}

public sealed class TranslationFile
{
    [JsonPropertyName("language")] public string Language { get; set; } = "da";
    [JsonPropertyName("source_language")] public string SourceLanguage { get; set; } = "en";
    [JsonPropertyName("strings")] public List<TranslationEntry> Strings { get; set; } = [];

    static readonly JsonSerializerOptions Options = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public static TranslationFile Load(string path) =>
        JsonSerializer.Deserialize<TranslationFile>(File.ReadAllText(path, Encoding.UTF8), Options) ?? new();

    public static TranslationFile Parse(string json) =>
        JsonSerializer.Deserialize<TranslationFile>(json, Options) ?? new();

    public void Save(string path)
    {
        var tmp = path + ".tmp";
        File.WriteAllText(tmp, JsonSerializer.Serialize(this, Options).Replace("\r\n", "\n"), new UTF8Encoding(false));
        File.Move(tmp, path, overwrite: true);
    }

    /// <summary>
    /// Merges a newer shipped translation into this (the user's working copy): entries the user
    /// edited are kept, everything else takes the shipped version, and new strings are added.
    /// </summary>
    public void MergeShipped(TranslationFile shipped)
    {
        var mine = Strings.ToDictionary(Key);
        var result = new List<TranslationEntry>();
        foreach (var s in shipped.Strings)
        {
            if (mine.Remove(Key(s), out var m) && m.Edited)
                result.Add(m);
            else
                result.Add(s);
        }
        // Keep the user's own additions (captured or hand-added strings) that the shipped file lacks.
        result.AddRange(mine.Values.Where(m => m.Edited || m.Confidence == "captured"));
        Strings = result;
    }

    static string Key(TranslationEntry e) => e.Kind + "\0" + e.En;

    /// <summary>Writes the XUnity.AutoTranslator text file for all translated entries.</summary>
    public string ToXUnity()
    {
        var sb = new StringBuilder();
        sb.Append("// Generated by MageQuit-DA Manager from strings.json. Edit translations in the Manager.\n");
        foreach (var e in Strings)
        {
            if (string.IsNullOrWhiteSpace(e.Da))
                continue;
            var da = e.UppercaseOnly ? e.Da.ToUpperInvariant() : e.Da;
            if (e.Kind is "regex" or "split")
                sb.Append(e.Kind == "split" ? "sr:\"" : "r:\"").Append(Escape(e.En)).Append("\"=").Append(Escape(da)).Append('\n');
            else
                sb.Append(Escape(e.En)).Append('=').Append(Escape(da)).Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>Escapes text for XUnity's KEY=VALUE format (see TextHelper.ReadTranslationLineAndDecode).</summary>
    internal static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '=': sb.Append(@"\="); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                // "//" starts an inline comment and "%3D" is a legacy '=' encoding; break both up.
                case '/' when i + 1 < s.Length && s[i + 1] == '/': sb.Append(@"\u002F"); break;
                case '%' when i + 2 < s.Length && s[i + 1] == '3' && s[i + 2] == 'D': sb.Append(@"\u0025"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    /// <summary>
    /// Imports strings recorded by the plugin's capture mode (captured.tsv). Strings already
    /// known (as English or as a Danish translation) are skipped. Returns the number added.
    /// </summary>
    public int ImportCaptured(string tsvPath)
    {
        var known = new HashSet<string>(Strings.Select(e => e.En));
        known.UnionWith(Strings.Where(e => e.Da.Length > 0).Select(e => e.UppercaseOnly ? e.Da.ToUpperInvariant() : e.Da));
        known.UnionWith(Strings.Where(e => e.Da.Length > 0).Select(e => e.Da));
        var regexes = Strings.Where(e => e.Kind is "regex" or "split" && e.En.Length > 0)
                             .Select(e => TryRegex(e.En)).Where(r => r != null).ToList();
        int added = 0;
        foreach (var line in File.ReadLines(tsvPath, Encoding.UTF8).Skip(1))
        {
            var f = line.Split('\t');
            if (f.Length < 5)
                continue;
            var text = Unescape(f[0]);
            if (known.Contains(text) || IsNumeric(text) || regexes.Any(r => r!.IsMatch(text)))
                continue;
            known.Add(text);
            Strings.Add(new TranslationEntry
            {
                En = text,
                Confidence = "captured",
                Sources = [$"{f[2]}: {Unescape(f[3])}"],
                Fonts = string.IsNullOrEmpty(f[1]) ? [] : [f[1]],
                UppercaseOnly = f[1] is "MageQuitHeaderThin" or "soupofjustice",
                Edited = true,
            });
            added++;
        }
        return added;
    }

    static System.Text.RegularExpressions.Regex? TryRegex(string pattern)
    {
        try { return new System.Text.RegularExpressions.Regex(pattern); }
        catch (ArgumentException) { return null; }
    }

    static bool IsNumeric(string s) =>
        !s.Any(char.IsLetter) || System.Text.RegularExpressions.Regex.IsMatch(s, @"^[\d\s.,:+\-/%xX]+[A-Za-z]{0,3}$");

    static string Unescape(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            if (s[i] == '\\' && i + 1 < s.Length)
            {
                var n = s[++i];
                sb.Append(n switch { 't' => '\t', 'n' => '\n', 'r' => '\r', _ => n });
            }
            else sb.Append(s[i]);
        }
        return sb.ToString();
    }
}
